### PR TITLE
Update for Xcode 8b4

### PR DESCRIPTION
**Pull request by robtimp**
Fix warnings in Xcode 8 beta 3.

### CODE REVIEW

**Comment by robtimp** [comment]
@masters3d Ok, I'll leave `GradeSchoolTest` as is for now.

How do you get SwiftLint to work properly with Xcode 8 and Swift 3? I get errors about lowercase enum case names, which is now the standard in Swift 3.

**Comment by masters3d** [comment]
Maybe Travis is not on the latest beta yet. 

`Testing failed:
	Boolean condition requires 'where' to separate it from variable binding
`

**Comment by masters3d** [comment]
Yeah. They are still on Beta2
Swift lint passed

https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

**Comment by masters3d** [comment]
image

**Comment by masters3d** [comment]
Yay Travis working again.

**Comment by masters3d** [comment]
Looks good to me. Squash merge when ready. Thanks!

**Comment by masters3d** [comment]
#166 You can squash merge in GitHub now. I use it all the time. it's great :)

**Pull request closed without merging**
