### PR TITLE
Add Binary Search Tree exercise

### PR DESCRIPTION
**Pull request by robtimp**
@masters3d I don't believe a solution is currently possible with structs (I get an error that `Recursive value type BinarySearchTree<T> is not allowed` when I try), but I'm using `var` instead of `let` just in case. 

Any thoughts on that?

### CODE REVIEW

**Comment by masters3d** [comment]
I'll take a look this evening. I know that for the linked list exercises I had to use a class eventhough a struct based solution was possible but it required jumping through many hoops.

**Comment by robtimp** [comment]
@masters3d Could also probably be done with an enum, using `indirect`, but a class is definitely the simplest solution.

**Comment by masters3d** [comment]
waynewbishop.com/swift/binary-search-trees/

Looks good, it's just a glorified Linked list. Thanks.

**Comment by masters3d** [comment]
Ah yeah, the new indirect enums would do it.

**Pull request merged**
