### PR TITLE
Add Nth Prime exercise

### PR DESCRIPTION
**Pull request by robtimp**
Add Nth Prime exercise

### CODE REVIEW

**Comment by masters3d** [comment]
Cool, could you add this exercise to the Xcode project so that Travis can can run?
Maybe later we can update Travis to use Xcode workspaces so files get added automatically to Travis.

**Comment by robtimp** [comment]
@masters3d No problem: I completely missed that there was an Xcode project at all!

**Comment by masters3d** [comment]
Nice. Yeah. I have been meaning to add it to the document section of the readme. Maybe once we make it Linux compatible when swift 3 comes out, we could come up with a different way for Travis to run the unit tests.

**Comment by masters3d** [comment]
Thank you.

**Pull request merged**
