### PR TITLE
Update INSTALLATION.md

### PR DESCRIPTION
**Pull request by bobdel**
This minor change adds a link to the Mac App Store.

### CODE REVIEW

**Comment by masters3d** [comment]
Thank you!

**Comment by bobdel** [comment]
I'm working on a longer version of the setup document, and would like to include images. I'm still pretty new to Github, so I'd welcome advice no matter how basic.

As I understand it, I should add an image to a message like this, then once its uploaded grab its URL. Is that correct?

**Comment by masters3d** [comment]
You are welcome to upload the images anywhere where they are known to have long retention of direct links. (Flickr, GitHub etc) I personally just like using GitHub which it is really a hack. 
https://github.com/exercism/xswift/pull/204
Perhaps the proper way would be to add the images to a folder and reference them that way. 
I'll leave that up to you. We have a logo images folder. 
Thanks again!

**Comment by masters3d** [comment]
https://github.com/exercism/xswift/tree/master/img
You are welcome to use this folder for documentation images.

**Comment by kytrinyx** [comment]
Yeah, for contributing documentation I think adding them to `img/` is the right thing.

**Comment by bobdel** [comment]
Since I don't have push access to that directory, how would I go about adding images to that directory?

**Comment by masters3d** [comment]
https://github.com/exercism/xswift/pull/214#issuecomment-265614616

**Comment by kytrinyx** [comment]
I am stranded at an airport, so my vacation is a bit delayed.

I was confused when I posted `img/`, I actually meant `docs/img`. But even this is broken. I've opened a PR so we can fix it. https://github.com/exercism/trackler/pull/15

**Comment by kytrinyx** [comment]
Wait. I'm confused about being confused.

Images in documentation about **contributing to the language track** should go in the top level `img/` directory.

Images in documentation **meant to be rendered on the exercism.io/languages/swift pages** (about how to get started solving the exercises in Swift) should go in `docs/img` (which you can create if it doesn't exist).

**Comment by masters3d** [comment]
Ah that clears it up. Thanks for the help.

**Pull request merged**
