### PR TITLE
Xcode documentation update

### PR DESCRIPTION
**Pull request by bobdel**
This is an updated version of the text using images stored in the repo directly.

### CODE REVIEW

**Comment by bobdel** [comment]
As I had expected using hello-world as a basis of the tutorial has some advantages and some issues. Mostly I think the way the hello-world exercise is delivered can be confusing to new users, esp those not used to digging around in Xcode project folders. I tried to write around the problems that crop up, but its awkward in places. 

Is it possible to modify the hello-world exercise? I propose putting all the Xcode project files in a folder "for experienced Xcoders." If we do that, that will make this tutorial less confusing and the learning curve flatter.

**Comment by masters3d** [comment]
I think the hello world Xcode project is not pulling its weight. This is not the first time that somebody says it's confusing. I am fine with deprecating the project given that people can follow a guide like this.

**Comment by masters3d** [comment]
https://github.com/exercism/xobjective-c/issues/27 

We have done with out the Xcode project in objective-c track. 

Plus Xcode should not be requirement for this track.

**Comment by masters3d** [comment]
Let me know when it is ready to merge so we can merge it. Thanks again!

**Comment by bobdel** [comment]
Is this directed at me?

**Comment by masters3d** [comment]
Sorry yeah :)

**Comment by bobdel** [comment]
No problem. Still getting the hang of etiquette here. I've been digging on using a GUI, upstream vs origin, etc. I want to redo the Hello-World exercise and edit the tutorial based on the simpler path structure. Most likely on Monday.

About your comment on not depending on Xcode. That's not really practical at the moment, right? Just a goal for when the open source stuff is a bit more polished?

**Comment by masters3d** [comment]
> About your comment on not depending on Xcode. That's not really practical at the moment, right? Just a goal for when the open source stuff is a bit more polished?

Yeah, there are other IDEs https://www.jetbrains.com/objc/ that currently support swift.

**Comment by bobdel** [comment]
This pull request is ready to merge

My apologies for the messy commit log. This is my first pull request, ever, and I'm still learning how both Git and Github works. I know a lot more than a did a week ago. Thanks!

All the comments and feedback this far have been incorporated into this request.

If preferable, I could make a fresh pull request with just the final version.

**Comment by masters3d** [comment]
Thank you!

**Pull request merged**
