### PR TITLE
Whitespace Cleanup

### PR DESCRIPTION
**Pull request by jonallured**
I know, I know, whitespace - who cares? It was just really bothering me that there was so much inconsistency, so I did my best to resist frivolous changes and stuck to mostly running:

Editor > Structure > Re-Indent

With 4 spaces as my indent. It's about as close as we can get to `gofmt` and seemed reasonable. Most of the files I saw matched this format anyway, many just had a mistake here or there.

Then I just went through and removed some bonus newlines. Ahhh, much better!! :sunglasses:

### CODE REVIEW

**Comment by masters3d** [comment]
Oh I know!  I wish we had a standard swift format tool like gofmt but we don't have that yet. 
https://github.com/exercism/xswift/issues/10

I am not sure what the stand is for exercism as a project on whitespace only PRs but this being a swift language track I am going to close this for now until we have an official swift linter. 

References:
https://github.com/apple/swift/pull/275
https://github.com/apple/swift/pull/963

**Comment by kytrinyx** [comment]
I think that if we are internally inconsistent, we could probably choose some sort of rule-set just for the repo, and be consistent with that (in which case whitespace-only PRs would totally be a good thing). I think the question is--are we inconsistent? If so, what sort of consistency is important? If we make it consistent, is there some sort of mini-linting that we could do to make it easy to keep things consistent (and also something that we could run on CI)?

**Comment by masters3d** [comment]
I would love a CI solution that makes a lint commit. . I have heard of something like that but I am not sure how to get it set up. I know travis can check lint rules but I don't know about actually making a "Lint" commit.  https://www.bignerdranch.com/blog/continuous-linting/

**Comment by jonallured** [comment]
Makes sense, I'll try to make progress on #10 instead. Thanks!! :D

**Pull request closed without merging**
