### PR TITLE
Fix SwiftLint warnings

### PR DESCRIPTION
**Pull request by robtimp**

### CODE REVIEW

**Comment by robtimp** [comment]
@masters3d

**Comment by regnerjr** [comment]
@robtimp Can we find an example of how the Swift team is formatting these? and choose to follow their style?

**Comment by masters3d** [comment]
I am fine with disabling the dictionary part of the rule. I don't think there is a consensus on this on the swift library codebase.

**Comment by robtimp** [comment]
@masters3d Ok, I'll open another PR to disable it.

Apple's Swift language book seems to use this format, but the language and standard library use either space on both sides or no spaces at all.

**Pull request closed without merging**
