### PR TITLE
update binary to return Optionals

### PR DESCRIPTION
**Pull request by masters3d**
https://github.com/exercism/x-common/issues/95

### CODE REVIEW

**Comment by hankturowski** [comment]
Your Travis integration is an amazing improvement.

**Comment by hankturowski** [comment]
I like this update a lot. We should do more with optionals.

**Comment by masters3d** [comment]
Thanks! Travis is cool. takes about 2-3 minutes to run though, not sure if that is normal. 
I was debating between throwing or optionals but I am not a fan of making all the callers have to use try try? for everything. 
http://ericasadun.com/2015/07/29/nils-vs-throws-in-swiftlang-part-ii/

**Comment by hankturowski** [comment]
I think that 2-3 minutes is a small price to pay for the added layer of protection. With the test running sequentially, I'm not surprised it takes that long.

I agree with you on try?. We should look through the exercises and see which ones might be good candidates for try blocks. Maybe we set up some specific error types to be returned? I kind of like the idea of an exercise that defines some things ahead of time and expects the user to conform. Like they're extending an existing system and can't touch the existing error types.

Maybe we can push a starter exercise.swift file with a predefined class and set of errors, then ask the user to extend it without touching the existing code.

**Comment by kytrinyx** [comment]
Travis might speed up if we configure it with `sudo: false` so that it uses containerized builds.

**Comment by masters3d** [comment]
i did try ```sudo: false``` on a test branch but not much improvement. I can live with 2-3 mins wait per pr. ;)

**Pull request merged**
