### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by masters3d**
Added `sudo: false`
https://github.com/exercism/xswift/pull/68

### CODE REVIEW

**Comment by masters3d** [comment]
Ah this makes sence. Sudo false only works for linux builds. 
https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
image

**Comment by kytrinyx** [comment]
oh, right. That does make sense.

**Comment by masters3d** [comment]
We can leave it on when we move the XCTest to Linux

**Comment by masters3d** [comment]
Do you know why there seems to be 2 instances of travis firing up?

image

**Comment by kytrinyx** [comment]
Yeah, one is on the branch itself, and one is on the PR. It's been doing that for a while.

**Comment by masters3d** [comment]
ah interesting, I never noticed. Thanks!

**Pull request merged**
