### PR TITLE
Fix issue #255

### PR DESCRIPTION
**Pull request by stevenhuey**
Here's a first shot at fixing issue #255 and my first PR for exercism. Please let me know if you need me to make any additional changes. Thanks!

### CODE REVIEW

**Comment by robtimp** [comment]
@stevenhuey Looks good.

Would you mind making these same changes to the `BobExample.swift` file? Otherwise, the tests will no longer pass.

**Comment by masters3d** [comment]
Thank you @stevenhuey ! This is great. Do you mind also changing the Example.swift file so that the tests pass?

**Comment by robtimp** [comment]
@stevenhuey :+1: Thanks for contributing!

**Comment by stevenhuey** [comment]
Thanks @robtimp . I really like the idea of exercism. I've worked through most of the Objective-C exercises and have started working on the Swift ones too. If I can fix anything else, I'll submit another PR.

**Pull request merged**
