### PR TITLE
Update Bowling tests for new spec

### LINKED ISSUE #194: Changes to Bowling tests
We recently rewrote the test suite for Bowling. Since this track implements Bowling, please [take a look at the new canonical_data.json file](https://github.com/exercism/x-common/blob/9049dc7f748fd038b140c878c4eaa89d09b73199/exercises/bowling/canonical-data.json) and see if your track should update its implementation or tests.

The new test suite reorders tests so that students can get to green quickly. It also reduces the number of tests so that students can focus on solving the interesting edge cases.

More details on this change are available in [this issue](https://github.com/exercism/x-common/issues/409)

### PR DESCRIPTION
**Pull request by robtimp**
Resolves #194 

* Update Bowling tests to match new canonical JSON: https://github.com/exercism/x-common/blob/9049dc7f748fd038b140c878c4eaa89d09b73199/exercises/bowling/canonical-data.json
* Fix a bug that was causing one of the new tests to fail (oops!)

### CODE REVIEW

**Comment by robtimp** [comment]
@masters3d

**Comment by masters3d** [comment]
Run the swiftLint autocorrect to get rid of trailing white space
image

**Comment by masters3d** [comment]
The bot is still showing trailing spaces. Xcode introduces them. SwiftLint can do this for you.

**Comment by robtimp** [comment]
@masters3d Ok, updated. It took me a while to figure out I needed to add a `.swift-version` file to get it to work.

**Comment by masters3d** [comment]
Sorry. The code looks good. The problem is Travis. They are still on xcode8gm and have not updated to 8.1 so that is why is giving out a weird message. Do you mind rolling back the version on Xcode to 3.0 instead of 3.0.1, that is why is its requiring the swift version file I believe. 

We are at the mercy of Travis here. I am not sure how to solve it.

**Comment by kytrinyx** [comment]
> The problem is Travis. They are still on xcode8gm and have not updated to 8.1 so that is why is giving out a weird message.

@robtimp @masters3d this sounds like something it would be worth documenting in the README.

**Pull request merged**
