### PR TITLE
10 problems Added

### PR DESCRIPTION
**Pull request by masters3d**
@hankturowski  Could you take at look at these five problems I implemented? 
Any feedback on the test is appreciated as I would like to continue with the rest on the list. 
I made that list comparing csharp's list and swift. ( I thought those tracks would be similar ).

Thanks

TODO:
- [X] sum-of-multiples
- [X] meetup
- [X] twelve-days
- [X] space-age
- [X] gigasecond
- [x] triangle
- [x] scrabble-score
- [X] roman-numerals
- [X] binary
- [X] prime-factor

### CODE REVIEW

**Comment by hankturowski** [comment]
Great work, @masters3d. I'll have a look through them as soon as I have a minute. The Ruby exercises are also a nice place to look for things to port over. Even if you don't use Ruby, the tests are very straight forward and easy to read.

**Comment by kytrinyx** [comment]
There's a synopsis of all the problems that are implemented across all the languages here: http://synopsis.exercism.io

We probably need to link to it from somewhere... not sure where people would look for it, though.

**Comment by masters3d** [comment]
I saw the synopsis which was very useful. I had a question about that before here
https://github.com/exercism/exercism.io/issues/2159
I also made a little script to help me make the above list. 
https://gist.github.com/masters3d/7427a1f7de4353f7bf71

@hankturowski Yeah I did notice ruby later on. Thanks for pointing that out. ( I was using python at first ). I think csharp examples are easy to implement back to swift. Hopefully that will speed things up.

**Comment by masters3d** [comment]
@hankturowski  I added a few more problems to this pull request. Let me know how I can help your review process. Thanks!

**Comment by hankturowski** [comment]
@masters3d Hey, things got a little bit crazy for me last week. I'll pull down your changes tonight and run them in my test environment. If everything looks okay, I'll merge everything in right after.

When I have some time I'll go through the code more closely and offer suggestions for changes if I have any.

I really appreciate your work here, and I'm very sorry for the delay.

**Comment by masters3d** [comment]
Sound good. No worries. Thank you for your help!

**Pull request merged**
